name: Update Canonical Tags

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-canonical-tags:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find and update canonical tags in HTML files
      run: |
        find . -name "*.html" | while read htmlFile; do
          tempFile="${htmlFile}.tmp"
          # Process the file to update canonical links
          awk '{
            if ($0 ~ /<link rel="canonical"/) {
              sub(/\.html"/, "\"", $0)
            }
            print $0
          }' "$htmlFile" > "$tempFile"
          mv "$tempFile" "$htmlFile"
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update canonical href tags in HTML files" || echo "No changes to commit"

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git push origin HEAD:main
